// b_GhJwr5TFeiz-1774103618949/components/mobile/mobile-profile.tsx
"use client"

import { useState } from "react"
import { 
  ArrowLeft,
  Settings,
  ChevronRight,
  BookHeart,
  MessageCircle,
  Heart,
  Award,
  Calendar,
  Bell,
  Moon,
  Shield,
  HelpCircle,
  LogOut,
  Camera,
  Star,
  TrendingUp,
  Flame,
  Target,
  Sparkles,
  Users,
  Edit3
} from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Progress } from "@/components/ui/progress"
import { Switch } from "@/components/ui/switch"

interface MobileProfileProps {
  onBack: () => void
}

export function MobileProfile({ onBack }: MobileProfileProps) {
  const [darkMode, setDarkMode] = useState(false)
  const [notifications, setNotifications] = useState(true)

  const stats = [
    { label: "连续签到", value: "15天", icon: Flame, color: "text-orange-500" },
    { label: "心情日记", value: "32篇", icon: BookHeart, color: "text-primary" },
    { label: "获得温暖", value: "128", icon: Heart, color: "text-red-500" },
    { label: "成就徽章", value: "8个", icon: Award, color: "text-amber-500" },
  ]

  const achievements = [
    { id: 1, name: "初次相遇", desc: "完成首次AI对话", icon: "🌟", unlocked: true },
    { id: 2, name: "坚持不懈", desc: "连续签到7天", icon: "🔥", unlocked: true },
    { id: 3, name: "倾诉者", desc: "累计对话100次", icon: "💬", unlocked: true },
    { id: 4, name: "暖心达人", desc: "在社区获得50个赞", icon: "💖", unlocked: true },
    { id: 5, name: "情绪管理师", desc: "记录30篇心情日记", icon: "📝", unlocked: true },
    { id: 6, name: "正念修行", desc: "完成10次冥想练习", icon: "🧘", unlocked: false },
  ]

  const menuItems = [
    { 
      group: "数据与记录",
      items: [
        { id: "diary", label: "我的日记", icon: BookHeart, badge: "32篇" },
        { id: "chat", label: "对话记录", icon: MessageCircle, badge: "156次" },
        { id: "collection", label: "我的收藏", icon: Heart },
        { id: "achievement", label: "成就中心", icon: Award, badge: "新" },
      ]
    },
    { 
      group: "设置",
      items: [
        { id: "notification", label: "消息通知", icon: Bell, toggle: true, value: notifications, onChange: setNotifications },
        { id: "dark", label: "深色模式", icon: Moon, toggle: true, value: darkMode, onChange: setDarkMode },
        { id: "privacy", label: "隐私设置", icon: Shield },
        { id: "help", label: "帮助与反馈", icon: HelpCircle },
      ]
    },
  ]

  return (
    <div className="flex flex-col min-h-screen bg-muted/30">
      {/* Header with Gradient Background */}
      <div className="relative bg-gradient-to-br from-primary via-primary/90 to-primary/80 pb-16">
        <header className="px-4 py-3 flex items-center justify-between">
          <Button variant="ghost" size="icon" onClick={onBack} className="text-primary-foreground hover:bg-primary-foreground/10">
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <span className="text-primary-foreground font-semibold">个人中心</span>
          <Button variant="ghost" size="icon" className="text-primary-foreground hover:bg-primary-foreground/10">
            <Settings className="h-5 w-5" />
          </Button>
        </header>

        {/* Profile Card */}
        <div className="px-4 pt-4">
          <div className="flex items-center gap-4">
            <div className="relative">
              <Avatar className="h-20 w-20 ring-4 ring-primary-foreground/30 shadow-xl">
                <AvatarImage src="/placeholder-user.jpg" alt="用户头像" />
                <AvatarFallback className="bg-primary-foreground text-primary text-2xl font-bold">李</AvatarFallback>
              </Avatar>
              <button className="absolute bottom-0 right-0 p-1.5 rounded-full bg-primary-foreground shadow-md">
                <Camera className="h-3.5 w-3.5 text-primary" />
              </button>
            </div>
            <div className="flex-1">
              <div className="flex items-center gap-2 mb-1">
                <h1 className="text-xl font-bold text-primary-foreground">李同学</h1>
                <Badge className="bg-primary-foreground/20 text-primary-foreground border-0 text-[10px]">
                  Lv.5
                </Badge>
              </div>
              <p className="text-primary-foreground/80 text-sm mb-2">保持好心情，每天都是新的开始</p>
              <div className="flex items-center gap-2">
                <Badge variant="secondary" className="bg-primary-foreground/20 text-primary-foreground border-0 gap-1">
                  <Star className="h-3 w-3 fill-amber-400 text-amber-400" />
                  暖心达人
                </Badge>
                <Badge variant="secondary" className="bg-primary-foreground/20 text-primary-foreground border-0">
                  计算机学院
                </Badge>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Stats Card - overlapping */}
      <div className="px-4 -mt-10 relative z-10">
        <Card className="border-0 shadow-lg">
          <CardContent className="p-4">
            <div className="grid grid-cols-4 gap-2">
              {stats.map((stat) => (
                <div key={stat.label} className="flex flex-col items-center">
                  <div className={`p-2 rounded-xl bg-muted mb-2`}>
                    <stat.icon className={`h-5 w-5 ${stat.color}`} />
                  </div>
                  <span className="text-base font-bold text-foreground">{stat.value}</span>
                  <span className="text-[10px] text-muted-foreground">{stat.label}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Main Content */}
      <main className="flex-1 px-4 py-4 space-y-4 pb-24">
        {/* Growth Progress */}
        <Card className="border border-border/60 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <Target className="h-4 w-4 text-primary" />
                <span className="text-sm font-semibold text-foreground">成长进度</span>
              </div>
              <span className="text-xs text-muted-foreground">距离下一等级还需 350 经验</span>
            </div>
            <Progress value={65} className="h-2 mb-2" />
            <div className="flex justify-between text-xs text-muted-foreground">
              <span>Lv.5 暖心达人</span>
              <span>650/1000 EXP</span>
              <span>Lv.6 治愈大师</span>
            </div>
          </CardContent>
        </Card>

        {/* Achievements Showcase */}
        <Card className="border border-border/60 shadow-sm">
          <CardContent className="p-4">
            <div className="flex items-center justify-between mb-3">
              <div className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-amber-500" />
                <span className="text-sm font-semibold text-foreground">成就展示</span>
              </div>
              <Button variant="ghost" size="sm" className="text-xs text-primary h-auto p-0">
                查看全部
                <ChevronRight className="h-3 w-3 ml-0.5" />
              </Button>
            </div>
            <div className="grid grid-cols-6 gap-2">
              {achievements.map((achievement) => (
                <div 
                  key={achievement.id} 
                  className={`flex flex-col items-center p-2 rounded-xl transition-all ${
                    achievement.unlocked 
                      ? "bg-gradient-to-b from-amber-50 to-orange-50" 
                      : "bg-muted opacity-50"
                  }`}
                >
                  <span className={`text-2xl mb-1 ${!achievement.unlocked && "grayscale"}`}>
                    {achievement.icon}
                  </span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Menu Groups */}
        {menuItems.map((group) => (
          <Card key={group.group} className="border border-border/60 shadow-sm">
            <CardContent className="p-0">
              <div className="px-4 py-2.5 border-b border-border/50">
                <span className="text-xs font-medium text-muted-foreground">{group.group}</span>
              </div>
              <div className="divide-y divide-border/50">
                {group.items.map((item) => (
                  <div
                    key={item.id}
                    className={`w-full flex items-center justify-between px-4 py-3.5 transition-colors ${
                      !item.toggle ? "hover:bg-muted/50 cursor-pointer" : ""
                    }`}
                    onClick={() => !item.toggle && console.log(`Navigate to ${item.id}`)}
                    role={!item.toggle ? "button" : undefined}
                    tabIndex={!item.toggle ? 0 : undefined}
                  >
                    <div className="flex items-center gap-3">
                      <div className="p-2 rounded-xl bg-muted">
                        <item.icon className="h-4 w-4 text-primary" />
                      </div>
                      <span className="text-sm font-medium text-foreground">{item.label}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      {item.badge && (
                        <Badge 
                          variant={item.badge === "新" ? "default" : "secondary"} 
                          className={`text-[10px] ${item.badge === "新" ? "bg-red-500" : ""}`}
                        >
                          {item.badge}
                        </Badge>
                      )}
                      {item.toggle ? (
                        <Switch 
                          checked={item.value} 
                          onCheckedChange={item.onChange}
                        />
                      ) : (
                        <ChevronRight className="h-4 w-4 text-muted-foreground" />
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        ))}

        {/* Logout Button */}
        <Button 
          variant="outline" 
          className="w-full h-12 text-destructive border-destructive/30 hover:bg-destructive/5 hover:text-destructive"
        >
          <LogOut className="h-4 w-4 mr-2" />
          退出登录
        </Button>

        {/* Version Info */}
        <p className="text-center text-xs text-muted-foreground pb-4">
          心灵伴侣 v1.0.0
        </p>
      </main>
    </div>
  )
}

// EasyPal/components/mobile/MobileProfile.vue
<template>
  <view class="profile">
    <header class="profile__header">
      <view class="profile__header-bar">
        <ui-button variant="ghost" size="icon" custom-class="profile__header-btn" @click="onBack">
          <ui-icon name="arrow-left" size="md" class="profile__header-icon" />
        </ui-button>
        <text class="profile__header-title">个人中心</text>
        <ui-button variant="ghost" size="icon" custom-class="profile__header-btn">
          <ui-icon name="settings" size="md" class="profile__header-icon" />
        </ui-button>
      </view>
      <view class="profile__info">
        <view class="profile__avatar-wrap">
          <ui-avatar size="lg" fallback-text="" custom-class="profile__avatar-main">
            <template #fallback>
              <ui-icon name="user" size="lg" class="profile__avatar-user-icon" />
            </template>
          </ui-avatar>
          <view class="profile__avatar-edit">
            <ui-icon name="camera" size="xs" class="profile__camera-icon" />
          </view>
        </view>
        <view class="profile__user-detail">
          <view class="profile__name-row">
            <text class="profile__user-name">李同学</text>
            <ui-badge variant="secondary" custom-class="profile__level-badge">Lv.5</ui-badge>
          </view>
          <text class="profile__user-sign">保持好心情，每天都是新的开始</text>
          <view class="profile__tags">
            <ui-badge variant="secondary" custom-class="profile__tag">
              <ui-icon name="award" size="xs" class="profile__tag-icon" />
              <text>暖心达人</text>
            </ui-badge>
            <ui-badge variant="secondary" custom-class="profile__tag">计算机学院</ui-badge>
          </view>
        </view>
      </view>
    </header>

    <view class="profile__stats-card">
      <view class="profile__stat-item">
        <view class="profile__stat-icon-wrap">
          <ui-icon name="flame" size="sm" class="profile__stat-icon profile__stat-icon--orange" />
        </view>
        <text class="profile__stat-value">15天</text>
        <text class="profile__stat-label">连续签到</text>
      </view>
      <view class="profile__stat-item">
        <view class="profile__stat-icon-wrap">
          <ui-icon name="book-heart" size="sm" class="profile__stat-icon profile__stat-icon--primary" />
        </view>
        <text class="profile__stat-value">32篇</text>
        <text class="profile__stat-label">心情日记</text>
      </view>
      <view class="profile__stat-item">
        <view class="profile__stat-icon-wrap">
          <ui-icon name="heart" size="sm" class="profile__stat-icon profile__stat-icon--red" />
        </view>
        <text class="profile__stat-value">128</text>
        <text class="profile__stat-label">获得温暖</text>
      </view>
      <view class="profile__stat-item">
        <view class="profile__stat-icon-wrap">
          <ui-icon name="award" size="sm" class="profile__stat-icon profile__stat-icon--amber" />
        </view>
        <text class="profile__stat-value">8个</text>
        <text class="profile__stat-label">成就徽章</text>
      </view>
    </view>

    <scroll-view scroll-y class="profile__main">
      <ui-card custom-class="profile__growth-card">
        <ui-card-content>
          <view class="profile__card-head">
            <view class="profile__card-title-wrap">
              <ui-icon name="target" size="sm" class="profile__card-emoji" />
              <text class="profile__card-title">成长进度</text>
            </view>
            <text class="profile__card-extra">距离下一等级还需350经验</text>
          </view>
          <ui-progress :value="65" custom-class="profile__progress" />
          <view class="profile__progress-labels">
            <text>Lv.5 暖心达人</text>
            <text class="profile__exp">650/1000 EXP</text>
            <text>Lv.6 治愈大师</text>
          </view>
        </ui-card-content>
      </ui-card>

      <ui-card custom-class="profile__achievement-card">
        <ui-card-content>
          <view class="profile__card-head">
            <view class="profile__card-title-wrap">
              <ui-icon name="award" size="sm" class="profile__card-emoji profile__card-emoji--amber" />
              <text class="profile__card-title">成就展示</text>
            </view>
            <text class="profile__card-link">查看全部 ›</text>
          </view>
          <view class="profile__achievement-grid">
            <view
              v-for="a in achievements"
              :key="a.id"
              class="profile__achievement-item"
              :class="{ 'profile__achievement-item--locked': !a.unlocked }"
            >
              <text class="profile__achievement-emoji">{{ a.icon }}</text>
            </view>
          </view>
        </ui-card-content>
      </ui-card>

      <view class="profile__menu-card">
        <view class="profile__menu-group">
          <text class="profile__group-title">数据与记录</text>
          <view class="profile__menu-item">
            <view class="profile__menu-left">
              <view class="profile__menu-icon-wrap">
                <ui-icon name="book-heart" size="sm" />
              </view>
              <text>我的日记</text>
            </view>
            <text class="profile__menu-badge">32篇</text>
            <ui-icon name="chevron-right" size="sm" class="profile__menu-arrow" />
          </view>
          <view class="profile__menu-item">
            <view class="profile__menu-left">
              <view class="profile__menu-icon-wrap">
                <ui-icon name="message-circle" size="sm" />
              </view>
              <text>对话记录</text>
            </view>
            <text class="profile__menu-badge">156次</text>
            <ui-icon name="chevron-right" size="sm" class="profile__menu-arrow" />
          </view>
          <view class="profile__menu-item">
            <view class="profile__menu-left">
              <view class="profile__menu-icon-wrap">
                <ui-icon name="heart" size="sm" />
              </view>
              <text>我的收藏</text>
            </view>
            <ui-icon name="chevron-right" size="sm" class="profile__menu-arrow" />
          </view>
          <view class="profile__menu-item">
            <view class="profile__menu-left">
              <view class="profile__menu-icon-wrap">
                <ui-icon name="award" size="sm" />
              </view>
              <text>成就中心</text>
            </view>
            <ui-badge variant="destructive" custom-class="profile__menu-badge--new">新</ui-badge>
            <ui-icon name="chevron-right" size="sm" class="profile__menu-arrow" />
          </view>
        </view>
        <view class="profile__menu-group">
          <text class="profile__group-title">设置</text>
          <view class="profile__menu-item">
            <view class="profile__menu-left">
              <view class="profile__menu-icon-wrap">
                <ui-icon name="bell" size="sm" />
              </view>
              <text>消息通知</text>
            </view>
            <ui-switch :checked="notifications" @change="(v) => (notifications = v)" />
          </view>
          <view class="profile__menu-item">
            <view class="profile__menu-left">
              <view class="profile__menu-icon-wrap">
                <ui-icon name="settings" size="sm" />
              </view>
              <text>深色模式</text>
            </view>
            <ui-switch :checked="darkMode" @change="(v) => (darkMode = v)" />
          </view>
          <view class="profile__menu-item">
            <view class="profile__menu-left">
              <view class="profile__menu-icon-wrap">
                <ui-icon name="lock" size="sm" />
              </view>
              <text>隐私设置</text>
            </view>
            <ui-icon name="chevron-right" size="sm" class="profile__menu-arrow" />
          </view>
          <view class="profile__menu-item">
            <view class="profile__menu-left">
              <view class="profile__menu-icon-wrap">
                <ui-icon name="message-circle" size="sm" />
              </view>
              <text>帮助与反馈</text>
            </view>
            <ui-icon name="chevron-right" size="sm" class="profile__menu-arrow" />
          </view>
        </view>
      </view>

      <view class="profile__logout-btn" @click="onLogout">
        <ui-icon name="log-out" size="sm" class="profile__logout-icon" />
        <text>退出登录</text>
      </view>
      <text class="profile__version">心灵伴侣 v1.0.0</text>
      <view class="profile__bottom-placeholder" />
    </scroll-view>
  </view>
</template>

<script setup>
import { ref } from 'vue'
import UiCard from '@/components/ui/Card.vue'
import UiCardContent from '@/components/ui/CardContent.vue'
import UiButton from '@/components/ui/Button.vue'
import UiAvatar from '@/components/ui/Avatar.vue'
import UiBadge from '@/components/ui/Badge.vue'
import UiProgress from '@/components/ui/Progress.vue'
import UiSwitch from '@/components/ui/Switch.vue'
import UiIcon from '@/components/ui/Icon.vue'

const emit = defineEmits(['back'])

const notifications = ref(true)
const darkMode = ref(false)

const achievements = [
  { id: 1, icon: '🌟', unlocked: true },
  { id: 2, icon: '🔥', unlocked: true },
  { id: 3, icon: '💬', unlocked: true },
  { id: 4, icon: '💖', unlocked: true },
  { id: 5, icon: '📝', unlocked: true },
  { id: 6, icon: '🧘', unlocked: false }
]

function onBack() { emit('back') }
function onLogout() {}
</script>

<style lang="scss" scoped>
@import '@/styles/variables.scss';

.profile {
  min-height: 100vh;
  background: #f5f9fa;
  padding-bottom: 120rpx;

  &__header {
    background: #1EB49F;
    padding: 24rpx 32rpx 88rpx;
    padding-top: calc(24rpx + env(safe-area-inset-top));
  }

  &__header-bar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 32rpx;
  }

  &__header-btn :deep(.ep-button) { background: transparent !important; }
  &__header-icon { color: #0f172a !important; }
  &__header-title { font-size: 40rpx; font-weight: 700; color: #0f172a; }

  &__info { display: flex; align-items: center; gap: 32rpx; }

  &__avatar-wrap {
    position: relative;
    flex-shrink: 0;
  }

  &__avatar-edit {
    position: absolute;
    bottom: 0;
    right: 0;
    width: 48rpx;
    height: 48rpx;
    border-radius: 50%;
    background: #f4fffd;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: $ep-shadow-sm;
  }

  &__camera-icon { color: $ep-primary !important; }
  &__avatar-user-icon { color: rgba(15, 23, 42, 0.55); }
  &__avatar-main :deep(.ep-avatar-fallback) {
    background: #ffffff;
  }

  &__user-detail { flex: 1; display: flex; flex-direction: column; gap: 12rpx; }
  &__name-row { display: flex; align-items: center; gap: 16rpx; }
  &__user-name { font-size: 50rpx; font-weight: 800; color: #0f172a; }
  &__level-badge { background: rgba(255, 255, 255, 0.35) !important; border: none; color: rgba(15, 23, 42, 0.75); }
  &__user-sign { font-size: 26rpx; color: rgba(255, 255, 255, 0.95); font-weight: 500; }
  &__tags { display: flex; gap: 16rpx; flex-wrap: wrap; }
  &__tag { background: rgba(255, 255, 255, 0.26) !important; border: none; color: rgba(15, 23, 42, 0.95); }
  &__tag-icon { color: #fbbf24 !important; margin-right: 4rpx; }

  &__stats-card {
    margin: -54rpx 32rpx 0;
    padding: 32rpx;
    background: #fff;
    border-radius: 28rpx;
    border: 1rpx solid rgba(15, 23, 42, 0.05);
    box-shadow: 0 12rpx 30rpx rgba(15, 23, 42, 0.08);
    display: flex;
    justify-content: space-around;
    position: relative;
    z-index: 10;
  }

  &__stat-item { display: flex; flex-direction: column; align-items: center; gap: 12rpx; }
  &__stat-icon-wrap {
    width: 72rpx;
    height: 72rpx;
    border-radius: 20rpx;
    background: #eaf1f3;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  &__stat-icon { color: $ep-primary; }
  &__stat-icon--orange { color: #f97316; }
  &__stat-icon--red { color: var(--ep-destructive); }
  &__stat-icon--amber { color: #f59e0b; }
  &__stat-value { font-size: 32rpx; font-weight: 700; color: var(--ep-foreground); }
  &__stat-label { font-size: 22rpx; color: var(--ep-muted-foreground); }

  &__main { padding: 28rpx; padding-top: 36rpx; min-height: 50vh; }

  &__growth-card, &__achievement-card { margin-bottom: 24rpx; }
  &__growth-card, &__achievement-card, &__menu-card {
    border-radius: 24rpx;
    border: 1rpx solid rgba(15, 23, 42, 0.06);
    background: #fff;
    box-shadow: 0 8rpx 20rpx rgba(15, 23, 42, 0.06);
  }
  &__card-head { display: flex; align-items: center; justify-content: space-between; margin-bottom: 20rpx; }
  &__card-title-wrap { display: flex; align-items: center; gap: 12rpx; }
  &__card-emoji { color: #00AB93; }
  &__card-emoji--amber { color: #f59e0b !important; }
  &__card-title { font-size: 28rpx; font-weight: 600; color: var(--ep-foreground); }
  &__card-extra { font-size: 22rpx; color: var(--ep-muted-foreground); }
  &__card-link { font-size: 24rpx; color: $ep-primary; }
  &__progress { margin-bottom: 16rpx; }
  &__progress :deep(.ep-progress__track) {
    background: #cde9e5;
  }
  &__progress :deep(.ep-progress__fill) {
    background: #00AB93;
  }
  &__progress-labels { display: flex; justify-content: space-between; font-size: 24rpx; color: var(--ep-muted-foreground); }
  &__exp { color: var(--ep-foreground); font-weight: 500; }

  &__achievement-grid {
    display: grid;
    grid-template-columns: repeat(6, 1fr);
    gap: 16rpx;
  }
  &__achievement-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 16rpx;
    border-radius: 16rpx;
    background: linear-gradient(180deg, #fef3c7 0%, #fed7aa 100%);
    &--locked { background: var(--ep-muted); opacity: 0.6; }
  }
  &__achievement-emoji { font-size: 48rpx; }
  &__achievement-item--locked &__achievement-emoji { filter: grayscale(1); }

  &__menu-card {
    background: #fff;
    border: 1rpx solid rgba(15, 23, 42, 0.06);
    border-radius: 24rpx;
    overflow: hidden;
    margin-bottom: 24rpx;
    box-shadow: 0 8rpx 20rpx rgba(15, 23, 42, 0.06);
  }
  &__menu-group { padding: 20rpx 32rpx 8rpx; }
  &__group-title { font-size: 24rpx; color: var(--ep-muted-foreground); font-weight: 500; display: block; margin-bottom: 16rpx; }
  &__menu-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 28rpx 0;
    border-top: 1rpx solid rgba(15, 23, 42, 0.08);
    border-bottom: 1rpx solid rgba(15, 23, 42, 0.08);
    &:last-child { border-bottom: none; }
  }
  &__menu-left { display: flex; align-items: center; gap: 24rpx; font-size: 28rpx; color: var(--ep-foreground); }
  &__menu-icon-wrap {
    width: 64rpx;
    height: 64rpx;
    border-radius: 16rpx;
    background: #E7F1F1;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  &__menu-icon-wrap :deep(.ep-icon) {
    color: #B9AC94;
  }
  &__menu-badge {
    font-size: 22rpx;
    color: rgba(15, 23, 42, 0.85);
    min-width: 86rpx;
    text-align: center;
    margin-right: 30rpx;
    margin-left: auto;
  }
  &__menu-badge--new { margin-right: 8rpx; }
  &__menu-arrow { color: var(--ep-muted-foreground); }

  &__logout-btn {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 12rpx;
    height: 96rpx;
    border: 1rpx solid rgba($ep-destructive, 0.4);
    border-radius: 16rpx;
    font-size: 30rpx;
    color: var(--ep-destructive);
    margin-bottom: 24rpx;
  }
  &__logout-icon { color: var(--ep-destructive) !important; }
  &__version { display: block; text-align: center; font-size: 24rpx; color: var(--ep-muted-foreground); margin-bottom: 24rpx; }
  &__bottom-placeholder { height: 40rpx; }
}
</style>
