// b_GhJwr5TFeiz-1774103618949/components/mobile/mobile-chat.tsx
"use client"

import { useState, useRef, useEffect } from "react"
import { 
  ArrowLeft, 
  Send, 
  Mic, 
  Camera, 
  MoreVertical,
  Sparkles,
  Heart,
  Volume2,
  Pause
} from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"

interface Message {
  id: number
  type: "user" | "ai"
  content: string
  emotion?: string
  timestamp: Date
}

interface MobileChatProps {
  onBack: () => void
}

export function MobileChat({ onBack }: MobileChatProps) {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: 1,
      type: "ai",
      content: "你好呀！我是你的AI心理陪伴助手小暖。今天感觉怎么样？有什么想和我聊聊的吗？🌸",
      timestamp: new Date(),
    },
  ])
  const [inputValue, setInputValue] = useState("")
  const [isRecording, setIsRecording] = useState(false)
  const [isTyping, setIsTyping] = useState(false)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  const handleSend = () => {
    if (!inputValue.trim()) return

    const userMessage: Message = {
      id: messages.length + 1,
      type: "user",
      content: inputValue,
      timestamp: new Date(),
    }

    setMessages((prev) => [...prev, userMessage])
    setInputValue("")
    setIsTyping(true)

    // Simulate AI response
    setTimeout(() => {
      const aiResponses = [
        "我理解你的感受。能具体说说是什么让你有这种感觉吗？我想更好地了解你。",
        "谢谢你愿意和我分享。你的感受是完全正常的，我们一起来看看可以做些什么。",
        "听起来你今天经历了不少。深呼吸一下，我陪着你慢慢聊。",
      ]

      const aiMessage: Message = {
        id: messages.length + 2,
        type: "ai",
        content: aiResponses[Math.floor(Math.random() * aiResponses.length)],
        emotion: "共情",
        timestamp: new Date(),
      }

      setIsTyping(false)
      setMessages((prev) => [...prev, aiMessage])
    }, 1500)
  }

  const quickReplies = [
    "我今天有点焦虑",
    "想聊聊学习压力",
    "最近睡眠不太好",
    "心情有些低落",
  ]

  return (
    <div className="flex flex-col h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-10 bg-card border-b border-border px-4 py-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="icon" onClick={onBack}>
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <Avatar className="h-9 w-9 ring-2 ring-primary/20">
              <AvatarImage src="/ai-avatar.png" alt="AI助手" />
              <AvatarFallback className="bg-primary text-primary-foreground">
                <Sparkles className="h-4 w-4" />
              </AvatarFallback>
            </Avatar>
            <div>
              <p className="font-semibold text-foreground text-sm">小暖</p>
              <p className="text-xs text-primary flex items-center gap-1">
                <span className="h-1.5 w-1.5 rounded-full bg-success animate-pulse" />
                AI心理陪伴助手
              </p>
            </div>
          </div>
          <Button variant="ghost" size="icon">
            <MoreVertical className="h-5 w-5" />
          </Button>
        </div>
      </header>

      {/* Messages */}
      <main className="flex-1 overflow-y-auto px-4 py-4 space-y-4">
        {/* Date Divider */}
        <div className="flex items-center gap-2 justify-center">
          <div className="h-px flex-1 bg-border" />
          <span className="text-xs text-muted-foreground px-2">今天</span>
          <div className="h-px flex-1 bg-border" />
        </div>

        {messages.map((message) => (
          <div
            key={message.id}
            className={`flex gap-2 ${message.type === "user" ? "flex-row-reverse" : ""}`}
          >
            {message.type === "ai" && (
              <Avatar className="h-8 w-8 shrink-0">
                <AvatarFallback className="bg-primary text-primary-foreground text-xs">
                  <Sparkles className="h-3 w-3" />
                </AvatarFallback>
              </Avatar>
            )}
            <div className={`max-w-[75%] ${message.type === "user" ? "items-end" : "items-start"}`}>
              <Card
                className={`border-0 ${
                  message.type === "user"
                    ? "bg-primary text-primary-foreground"
                    : "bg-card shadow-sm"
                }`}
              >
                <CardContent className="p-3">
                  <p className="text-sm leading-relaxed">{message.content}</p>
                </CardContent>
              </Card>
              <div className={`flex items-center gap-2 mt-1 px-1 ${message.type === "user" ? "justify-end" : ""}`}>
                <span className="text-[10px] text-muted-foreground">
                  {message.timestamp.toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" })}
                </span>
                {message.type === "ai" && message.emotion && (
                  <span className="text-[10px] text-primary bg-primary/10 px-1.5 py-0.5 rounded">
                    {message.emotion}
                  </span>
                )}
                {message.type === "ai" && (
                  <button className="text-muted-foreground hover:text-primary transition-colors">
                    <Volume2 className="h-3 w-3" />
                  </button>
                )}
              </div>
            </div>
          </div>
        ))}

        {isTyping && (
          <div className="flex gap-2">
            <Avatar className="h-8 w-8 shrink-0">
              <AvatarFallback className="bg-primary text-primary-foreground text-xs">
                <Sparkles className="h-3 w-3" />
              </AvatarFallback>
            </Avatar>
            <Card className="border-0 bg-card shadow-sm">
              <CardContent className="p-3">
                <div className="flex gap-1">
                  <span className="h-2 w-2 rounded-full bg-muted-foreground animate-bounce" style={{ animationDelay: "0ms" }} />
                  <span className="h-2 w-2 rounded-full bg-muted-foreground animate-bounce" style={{ animationDelay: "150ms" }} />
                  <span className="h-2 w-2 rounded-full bg-muted-foreground animate-bounce" style={{ animationDelay: "300ms" }} />
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        <div ref={messagesEndRef} />
      </main>

      {/* Quick Replies */}
      {messages.length <= 2 && (
        <div className="px-4 py-2 overflow-x-auto">
          <div className="flex gap-2">
            {quickReplies.map((reply, i) => (
              <Button
                key={i}
                variant="outline"
                size="sm"
                className="shrink-0 text-xs rounded-full border-primary/30 text-primary hover:bg-primary/10"
                onClick={() => setInputValue(reply)}
              >
                {reply}
              </Button>
            ))}
          </div>
        </div>
      )}

      {/* Input Area */}
      <div className="sticky bottom-0 bg-card border-t border-border p-4">
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="icon" className="shrink-0 text-muted-foreground hover:text-primary">
            <Camera className="h-5 w-5" />
          </Button>
          <div className="flex-1 relative">
            <Input
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSend()}
              placeholder="说点什么..."
              className="pr-10 rounded-full bg-muted border-0"
            />
          </div>
          <Button
            variant="ghost"
            size="icon"
            className={`shrink-0 transition-colors ${isRecording ? "text-destructive" : "text-muted-foreground hover:text-primary"}`}
            onClick={() => setIsRecording(!isRecording)}
          >
            {isRecording ? <Pause className="h-5 w-5" /> : <Mic className="h-5 w-5" />}
          </Button>
          <Button
            size="icon"
            onClick={handleSend}
            disabled={!inputValue.trim()}
            className="shrink-0 rounded-full"
          >
            <Send className="h-4 w-4" />
          </Button>
        </div>
        {isRecording && (
          <div className="mt-2 flex items-center justify-center gap-2 text-sm text-destructive">
            <span className="h-2 w-2 rounded-full bg-destructive animate-pulse" />
            正在录音...点击停止
          </div>
        )}
      </div>
    </div>
  )
}

// EasyPal/components/mobile/MobileChat.vue
<template>
  <view class="chat">
    <header class="chat__header">
      <view class="chat__header-left">
        <ui-button variant="ghost" size="icon" @click="onBack">
          <ui-icon name="arrow-left" size="md" />
        </ui-button>
        <ui-avatar size="sm" fallback-text="" custom-class="chat__avatar">
          <template #fallback>
            <ui-icon name="sparkles" size="sm" class="chat__avatar-icon" />
          </template>
        </ui-avatar>
        <view class="chat__ai-info">
          <text class="chat__ai-name">小暖</text>
          <view class="chat__ai-tag">
            <view class="chat__dot" />
            <text class="chat__ai-desc">AI心理陪伴助手</text>
          </view>
        </view>
      </view>
      <ui-button variant="ghost" size="icon">
        <ui-icon name="more-vertical" size="md" />
      </ui-button>
    </header>

    <scroll-view
      scroll-y
      class="chat__message-list"
      :scroll-into-view="scrollToId"
      scroll-with-animation
    >
      <view class="chat__date-divider">
        <view class="chat__line" />
        <text class="chat__date-text">今天</text>
        <view class="chat__line" />
      </view>

      <view
        v-for="msg in messages"
        :id="'msg-' + msg.id"
        :key="msg.id"
        class="chat__message-row"
        :class="'chat__message-row--' + msg.type"
      >
        <view v-if="msg.type === 'ai'" class="chat__msg-avatar">
          <ui-avatar size="sm" fallback-text="">
            <template #fallback>
              <ui-icon name="sparkles" size="xs" class="chat__avatar-icon" />
            </template>
          </ui-avatar>
        </view>
        <view class="chat__bubble-wrap">
          <ui-card :custom-class="'chat__bubble chat__bubble--' + msg.type">
            <ui-card-content>
              <text class="chat__bubble-text">{{ msg.content }}</text>
            </ui-card-content>
          </ui-card>
          <view class="chat__meta-row" :class="'chat__meta-row--' + msg.type">
            <text class="chat__time">{{ formatTime(msg.timestamp) }}</text>
            <ui-badge v-if="msg.type === 'ai' && msg.emotion" variant="secondary" custom-class="chat__emotion-tag">
              {{ msg.emotion }}
            </ui-badge>
            <view v-if="msg.type === 'ai'" class="chat__volume-btn">
              <ui-icon name="volume-2" size="xs" />
            </view>
          </view>
        </view>
      </view>

      <view v-if="isTyping" class="chat__message-row chat__message-row--ai">
        <view class="chat__msg-avatar">
          <ui-avatar size="sm" fallback-text="">
            <template #fallback>
              <ui-icon name="sparkles" size="xs" class="chat__avatar-icon" />
            </template>
          </ui-avatar>
        </view>
        <view class="chat__typing-bubble">
          <view class="chat__typing-dot" />
          <view class="chat__typing-dot" />
          <view class="chat__typing-dot" />
        </view>
      </view>

      <view id="msg-end" class="chat__scroll-anchor" />
    </scroll-view>

    <view class="chat__bottom">
      <view v-if="messages.length <= 2" class="chat__quick-replies">
        <scroll-view scroll-x class="chat__quick-scroll" :show-scrollbar="false">
          <ui-button
            v-for="(reply, i) in quickReplies"
            :key="i"
            variant="outline"
            size="sm"
            custom-class="chat__quick-item"
            @click="inputValue = reply"
          >
            <text>{{ reply }}</text>
          </ui-button>
        </scroll-view>
      </view>

      <view class="chat__input-bar">
        <view class="chat__input-row">
          <ui-button variant="ghost" size="icon">
            <ui-icon name="camera" size="md" />
          </ui-button>
          <ui-input
            v-model="inputValue"
            placeholder="说点什么..."
            custom-class="chat__input"
            @confirm="handleSend"
          />
          <ui-button
            variant="ghost"
            size="icon"
            :custom-class="isRecording ? 'chat__mic--recording' : ''"
            @click="isRecording = !isRecording"
          >
            <ui-icon name="mic" size="md" />
          </ui-button>
          <view
            class="chat__send-btn"
            :class="{ 'chat__send-btn--active': !!inputValue.trim() }"
            @click="handleSend"
          >
            <ui-icon name="send" size="sm" class="chat__send-icon" />
          </view>
        </view>
        <view v-if="isRecording" class="chat__recording-tip">
          <view class="chat__rec-dot" />
          <text>正在录音...点击停止</text>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup>
import { ref, nextTick } from 'vue'
import UiCard from '@/components/ui/Card.vue'
import UiCardContent from '@/components/ui/CardContent.vue'
import UiButton from '@/components/ui/Button.vue'
import UiAvatar from '@/components/ui/Avatar.vue'
import UiBadge from '@/components/ui/Badge.vue'
import UiInput from '@/components/ui/Input.vue'
import UiIcon from '@/components/ui/Icon.vue'

const emit = defineEmits(['back'])

const messages = ref([
  {
    id: 1,
    type: 'ai',
    content: '你好呀！我是你的AI心理陪伴助手小暖。今天感觉怎么样？有什么想和我聊聊的吗？🌸',
    timestamp: new Date(),
    emotion: null
  }
])
const inputValue = ref('')
const isRecording = ref(false)
const isTyping = ref(false)
const scrollToId = ref('')

const quickReplies = [
  '我今天有点焦虑',
  '想聊聊学习压力',
  '最近睡眠不太好',
  '心情有些低落'
]

const aiReplies = [
  '我理解你的感受。能具体说说是什么让你有这种感觉吗？我想更好地了解你。',
  '谢谢你愿意和我分享。你的感受是完全正常的，我们一起来看看可以做些什么。',
  '听起来你今天经历了不少。深呼吸一下，我陪着你慢慢聊。'
]

function formatTime(date) {
  const d = date instanceof Date ? date : new Date(date)
  const h = d.getHours()
  const m = d.getMinutes()
  return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}`
}

function onBack() {
  emit('back')
}

async function handleSend() {
  const text = inputValue.value.trim()
  if (!text) return

  const userMsg = {
    id: messages.value.length + 1,
    type: 'user',
    content: text,
    timestamp: new Date()
  }
  messages.value.push(userMsg)
  inputValue.value = ''
  isTyping.value = true
  nextTick(() => { scrollToId.value = 'msg-end' })

  await new Promise(r => setTimeout(r, 1500))

  const aiMsg = {
    id: messages.value.length + 1,
    type: 'ai',
    content: aiReplies[Math.floor(Math.random() * aiReplies.length)],
    emotion: '共情',
    timestamp: new Date()
  }
  messages.value.push(aiMsg)
  isTyping.value = false
  nextTick(() => { scrollToId.value = 'msg-end' })
}
</script>

<style lang="scss" scoped>
@import '@/styles/variables.scss';

.chat {
  min-height: 100vh;
  background: #F5F9FA;
  display: flex;
  flex-direction: column;
  padding-bottom: 0;

  &__header {
    position: sticky;
    top: 0;
    z-index: 10;
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 24rpx 32rpx;
    background: #ffffff;
    border-bottom: 1rpx solid rgba(15, 23, 42, 0.06);
  }

  &__header-left {
    display: flex;
    align-items: center;
    gap: 24rpx;
  }

  &__avatar {
    flex-shrink: 0;
  }

  &__avatar :deep(.ep-avatar-fallback) {
    background: #00AB93;
    color: #fff;
  }

  &__avatar-icon {
    color: #fff;
  }

  &__ai-info {
    display: flex;
    flex-direction: column;
    gap: 4rpx;
  }

  &__ai-name {
    font-size: 28rpx;
    font-weight: 600;
    color: var(--ep-foreground);
  }

  &__ai-tag {
    display: flex;
    align-items: center;
    gap: 8rpx;
  }

  &__dot {
    width: 12rpx;
    height: 12rpx;
    border-radius: 50%;
    background: $ep-primary;
    animation: chat-pulse 1.5s infinite;
  }

  &__ai-desc {
    font-size: 22rpx;
    color: $ep-primary;
  }

  &__message-list {
    flex: 1;
    height: 0;
    padding: 20rpx 22rpx 312rpx;
  }

  &__date-divider {
    display: flex;
    align-items: center;
    gap: 20rpx;
    margin: 8rpx 0 26rpx;
  }

  &__line {
    flex: 1;
    height: 1rpx;
    background: rgba(15, 23, 42, 0.12);
  }

  &__date-text {
    font-size: 24rpx;
    color: rgba(15, 23, 42, 0.55);
    font-weight: 600;
  }

  &__message-row {
    display: flex;
    gap: 14rpx;
    margin-bottom: 22rpx;

    &--user {
      flex-direction: row-reverse;
    }
  }

  &__msg-avatar {
    flex-shrink: 0;
  }

  &__msg-avatar :deep(.ep-avatar-fallback) {
    background: #00AB93;
    color: #fff;
  }

  &__bubble-wrap {
    max-width: 82%;
    display: flex;
    flex-direction: column;
    align-items: flex-start;
  }

  &__message-row--user &__bubble-wrap {
    align-items: flex-end;
  }

  &__bubble {
    padding: 0;
    border: 1rpx solid rgba(15, 23, 42, 0.04);
    box-shadow: 0 6rpx 14rpx rgba(15, 23, 42, 0.05);
    max-width: 100%;
    border-radius: 26rpx;

    &--ai {
      background: #fff;
    }

    &--user {
      background: $ep-primary;
      color: var(--ep-primary-foreground);
    }
  }

  &__bubble-text {
    font-size: 28rpx;
    line-height: 1.52;
    color: inherit;
  }

  &__bubble :deep(.ep-card-content) {
    padding: 30rpx 26rpx;
  }

  &__meta-row {
    display: flex;
    align-items: center;
    gap: 12rpx;
    margin-top: 6rpx;
    padding: 0 8rpx;

    &--user {
      justify-content: flex-end;
    }
  }

  &__time {
    font-size: 20rpx;
    color: rgba(15, 23, 42, 0.58);
  }

  &__emotion-tag {
    font-size: 20rpx;
  }

  &__volume-btn {
    color: var(--ep-muted-foreground);
  }

  &__typing-bubble {
    display: flex;
    align-items: center;
    gap: 8rpx;
    padding: 24rpx 28rpx;
    background: var(--ep-card);
    border-radius: 20rpx;
    box-shadow: $ep-shadow-sm;
  }

  &__typing-dot {
    width: 16rpx;
    height: 16rpx;
    border-radius: 50%;
    background: var(--ep-muted-foreground);
    animation: chat-bounce 0.6s ease-in-out infinite;

    &:nth-child(2) { animation-delay: 0.1s; }
    &:nth-child(3) { animation-delay: 0.2s; }
  }

  &__scroll-anchor {
    height: 1rpx;
  }

  &__bottom {
    position: fixed;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 20;
    background: transparent;
    border-top: 0;
  }

  &__quick-replies {
    padding: 12rpx 10rpx 14rpx;
    background: transparent;
  }

  &__quick-scroll {
    white-space: nowrap;
  }

  &__quick-item {
    margin-right: 14rpx;
    border-color: #9BDCD5;
    color: #F5F9FA;
    background: #f8fbfb;
    border-radius: 999rpx;
    font-weight: 500;
    padding: 10rpx 20rpx !important;
    transition: background-color 0.2s ease, border-color 0.2s ease;
  }

  &__quick-item:hover,
  &__quick-item:active {
    background: #DDF2F0;
    color: #000;
    border-color: #9BDCD5;
  }

  &__input-bar {
    margin-top: 8rpx;
    padding: 12rpx 14rpx;
    padding-bottom: calc(14rpx + env(safe-area-inset-bottom));
    background: #fff;
    border-top: 1rpx solid rgba(15, 23, 42, 0.08);
  }

  &__input-row {
    display: flex;
    align-items: center;
    gap: 12rpx;
  }

  &__input {
    flex: 1;
    border-radius: 999rpx !important;
    background: #edf3f4 !important;
    min-height: 74rpx !important;
  }

  :deep(.chat__input.ep-input) {
    border: 2rpx solid transparent !important;
    transition: border-color 0.2s ease, background-color 0.2s ease;
  }

  :deep(.chat__input.ep-input:focus) {
    border-color: #66CFC1 !important;
    background: #fff !important;
  }

  &__send-btn {
    width: 74rpx;
    height: 74rpx;
    border-radius: 50%;
    background: #7FD5C9;
    display: flex;
    align-items: center;
    justify-content: center;

    &--active {
      background: #00AB93;
    }
  }

  &__send-icon {
    color: #fff !important;
  }

  &__recording-tip {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 12rpx;
    margin-top: 16rpx;
    font-size: 24rpx;
    color: var(--ep-destructive);
  }

  &__rec-dot {
    width: 16rpx;
    height: 16rpx;
    border-radius: 50%;
    background: var(--ep-destructive);
    animation: chat-pulse 1s infinite;
  }
}

@keyframes chat-pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

@keyframes chat-bounce {
  0%, 100% { transform: translateY(0); }
  50% { transform: translateY(-8rpx); }
}
</style>
