// EasyPal/components/mobile/MobileDiary.vue
<template>
  <view class="diary">
    <template v-if="isWriting">
      <header class="diary__header">
        <text class="diary__nav-btn" @click="isWriting = false">取消</text>
        <text class="diary__header-title">写日记</text>
        <text class="diary__nav-btn" :class="{ 'diary__nav-btn--disabled': !canPublish }">发布</text>
      </header>
      <scroll-view scroll-y class="diary__write-content">
        <view class="diary__form-section">
          <text class="diary__form-label">今天的心情</text>
          <view class="diary__option-row">
            <view
              v-for="m in moodOptions"
              :key="m.id"
              class="diary__option-chip"
              :class="{ 'diary__option-chip--active': selectedMood === m.id }"
              @click="selectedMood = m.id"
            >
              <ui-icon :name="m.icon" size="sm" class="diary__option-icon" />
              <text>{{ m.label }}</text>
            </view>
          </view>
        </view>
        <view class="diary__form-section">
          <text class="diary__form-label">今天的天气</text>
          <view class="diary__option-row">
            <view
              v-for="w in weatherOptions"
              :key="w.id"
              class="diary__option-chip"
              :class="{ 'diary__option-chip--active': selectedWeather === w.id }"
              @click="selectedWeather = w.id"
            >
              <ui-icon :name="w.icon" size="sm" class="diary__option-icon" />
              <text>{{ w.label }}</text>
            </view>
          </view>
        </view>
        <view class="diary__form-section">
          <text class="diary__form-label">写下今天的心情...</text>
          <ui-textarea
            v-model="diaryContent"
            placeholder="今天发生了什么？你的感受如何？"
            custom-class="diary__textarea"
          />
        </view>
        <view class="diary__form-actions">
          <view class="diary__action-btn">
            <ui-icon name="image" size="sm" />
            <text>添加图片</text>
          </view>
          <view
            class="diary__action-btn"
            :class="{ 'diary__action-btn--active': !isPrivate }"
            @click="isPrivate = !isPrivate"
          >
            <ui-icon :name="isPrivate ? 'lock' : 'unlock'" size="sm" />
            <text>{{ isPrivate ? '仅自己可见' : '分享到社区' }}</text>
          </view>
        </view>
      </scroll-view>
    </template>

    <template v-else>
      <header class="diary__header">
        <view class="diary__header-left">
          <ui-button variant="ghost" size="icon" @click="onBack">
            <ui-icon name="arrow-left" size="md" />
          </ui-button>
          <text class="diary__header-title">心情日记</text>
        </view>
        <ui-button variant="ghost" size="icon">
          <ui-icon name="calendar" size="md" />
        </ui-button>
      </header>

      <view class="diary__stats-card">
        <view class="diary__stat-item">
          <text class="diary__stat-num">28</text>
          <text class="diary__stat-label">累计记录</text>
        </view>
        <view class="diary__stat-divider" />
        <view class="diary__stat-item">
          <text class="diary__stat-num">7</text>
          <text class="diary__stat-label">连续天数</text>
        </view>
        <view class="diary__stat-divider" />
        <view class="diary__stat-item">
          <text class="diary__stat-num diary__stat-num--green">68%</text>
          <text class="diary__stat-label">积极情绪</text>
        </view>
      </view>

      <scroll-view scroll-y class="diary__list">
        <ui-card
          v-for="entry in diaryEntries"
          :key="entry.id"
          custom-class="diary__card"
          @click="openDetail(entry)"
        >
          <ui-card-header>
            <view class="diary__card-head">
              <view class="diary__meta">
                <text class="diary__date">{{ entry.date }}</text>
                <ui-icon :name="getMoodIcon(entry.mood)" size="xs" class="diary__mood-icon" />
                <ui-icon :name="getWeatherIcon(entry.weather)" size="xs" class="diary__weather-icon" />
              </view>
              <view class="diary__card-right">
                <template v-if="entry.isPrivate">
                  <ui-icon name="lock" size="xs" class="diary__lock-icon" />
                </template>
                <template v-else>
                  <ui-icon name="heart" size="xs" class="diary__like-icon" />
                  <text class="diary__like-num">{{ entry.likes }}</text>
                </template>
                <ui-icon name="chevron-right" size="xs" class="diary__arrow" />
              </view>
            </view>
          </ui-card-header>
          <ui-card-content>
            <text class="diary__preview">{{ entry.content }}</text>
          </ui-card-content>
        </ui-card>
      </scroll-view>

      <view class="diary__fab" @click="isWriting = true">
        <text class="diary__fab-icon">+</text>
      </view>
    </template>
    <view class="diary__bottom-placeholder" />
  </view>
</template>

<script setup>
import { ref, computed } from 'vue'
import UiCard from '@/components/ui/Card.vue'
import UiCardHeader from '@/components/ui/CardHeader.vue'
import UiCardContent from '@/components/ui/CardContent.vue'
import UiButton from '@/components/ui/Button.vue'
import UiTextarea from '@/components/ui/Textarea.vue'
import UiIcon from '@/components/ui/Icon.vue'

const emit = defineEmits(['back'])

const isWriting = ref(false)
const selectedMood = ref(null)
const selectedWeather = ref(null)
const diaryContent = ref('')
const isPrivate = ref(true)

const canPublish = computed(() => diaryContent.value.trim() && selectedMood.value)

const moodOptions = [
  { id: 'happy', icon: 'smile', label: '开心' },
  { id: 'neutral', icon: 'meh', label: '平静' },
  { id: 'sad', icon: 'frown', label: '低落' }
]

const weatherOptions = [
  { id: 'sunny', icon: 'sun', label: '晴天' },
  { id: 'cloudy', icon: 'cloud', label: '阴天' },
  { id: 'rainy', icon: 'cloud-rain', label: '雨天' }
]

const diaryEntries = [
  { id: 1, date: '今天', mood: 'happy', weather: 'sunny', content: '今天和室友一起去图书馆学习，效率很高！晚上还一起吃了火锅，感觉生活充满了小确幸。', isPrivate: false, likes: 12 },
  { id: 2, date: '昨天', mood: 'neutral', weather: 'cloudy', content: '普通的一天，上课、作业、自习。虽然有些疲惫，但一切都在正轨上。', isPrivate: true },
  { id: 3, date: '3月12日', mood: 'sad', weather: 'rainy', content: '考试没考好，有点失落。不过想想还有机会补救，给自己打打气吧。', isPrivate: true }
]

function getMoodIcon(mood) {
  const map = { happy: 'smile', neutral: 'meh', sad: 'frown' }
  return map[mood] || 'meh'
}

function getWeatherIcon(weather) {
  const map = { sunny: 'sun', cloudy: 'cloud', rainy: 'cloud-rain' }
  return map[weather] || 'sun'
}

function onBack() { emit('back') }
function openDetail() {}
</script>

<style lang="scss" scoped>
@import '@/styles/variables.scss';

.diary {
  min-height: 100vh;
  background: #F5F9FA;
  padding-bottom: 120rpx;

  &__header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 24rpx 32rpx;
    background: var(--ep-card);
    border-bottom: 1rpx solid var(--ep-border);
  }

  &__header-left {
    display: flex;
    align-items: center;
    gap: 24rpx;
  }

  &__header-title {
    font-size: 34rpx;
    font-weight: 600;
    color: var(--ep-foreground);
  }

  &__nav-btn {
    font-size: 28rpx;
    color: $ep-primary;
    &--disabled { color: var(--ep-muted-foreground); }
  }

  &__write-content {
    padding: 32rpx;
    min-height: 60vh;
  }

  &__form-section {
    margin-bottom: 40rpx;
  }

  &__form-label {
    display: block;
    font-size: 28rpx;
    font-weight: 500;
    color: var(--ep-foreground);
    margin-bottom: 20rpx;
  }

  &__option-row {
    display: flex;
    flex-wrap: wrap;
    gap: 20rpx;
  }

  &__option-chip {
    display: flex;
    align-items: center;
    gap: 12rpx;
    padding: 16rpx 28rpx;
    border: 1rpx solid var(--ep-border);
    border-radius: 40rpx;
    font-size: 26rpx;
    color: var(--ep-muted-foreground);
    &--active {
      background: rgba($ep-primary, 0.1);
      border-color: $ep-primary;
      color: $ep-primary;
    }
  }

  &__option-icon {
    flex-shrink: 0;
  }

  &__textarea {
    min-height: 320rpx;
  }

  &__form-actions {
    display: flex;
    justify-content: space-between;
    padding: 24rpx 0;
  }

  &__action-btn {
    display: flex;
    align-items: center;
    gap: 12rpx;
    font-size: 26rpx;
    color: var(--ep-muted-foreground);
    &--active { color: $ep-primary; }
  }

  &__stats-card {
    margin: 24rpx 32rpx;
    padding: 32rpx;
    background: linear-gradient(135deg, rgba($ep-primary, 0.1) 0%, rgba($ep-accent, 0.1) 100%);
    border-radius: 24rpx;
    display: flex;
    align-items: center;
    justify-content: space-around;
  }

  &__stat-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8rpx;
  }

  &__stat-num {
    font-size: 48rpx;
    font-weight: 700;
    color: var(--ep-foreground);
    &--green { color: $ep-success; }
  }

  &__stat-label {
    font-size: 24rpx;
    color: var(--ep-muted-foreground);
  }

  &__stat-divider {
    width: 1rpx;
    height: 60rpx;
    background: var(--ep-border);
  }

  &__list {
    padding: 0 32rpx 32rpx;
    min-height: 50vh;
  }

  &__card {
    margin-bottom: 24rpx;
  }

  &__card-head {
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  &__meta {
    display: flex;
    align-items: center;
    gap: 12rpx;
  }

  &__date {
    font-size: 28rpx;
    font-weight: 500;
    color: var(--ep-foreground);
  }

  &__mood-icon, &__weather-icon, &__lock-icon, &__like-icon {
    color: var(--ep-muted-foreground);
  }

  &__like-icon { color: var(--ep-destructive); }

  &__card-right {
    display: flex;
    align-items: center;
    gap: 8rpx;
  }

  &__like-num {
    font-size: 24rpx;
    color: var(--ep-muted-foreground);
  }

  &__arrow {
    color: var(--ep-muted-foreground);
  }

  &__preview {
    font-size: 26rpx;
    color: var(--ep-muted-foreground);
    line-height: 1.5;
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }

  &__fab {
    position: fixed;
    right: 32rpx;
    bottom: 140rpx;
    width: 112rpx;
    height: 112rpx;
    border-radius: 50%;
    background: $ep-primary;
    box-shadow: 0 8rpx 24rpx rgba($ep-primary, 0.4);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 20;
  }

  &__fab-icon {
    font-size: 56rpx;
    color: var(--ep-primary-foreground);
    line-height: 1;
    font-weight: 300;
  }

  &__bottom-placeholder {
    height: 40rpx;
  }
}
</style>

// b_GhJwr5TFeiz-1774103618949/components/mobile/mobile-diary.tsx
"use client"

import { useState } from "react"
import { 
  ArrowLeft, 
  Plus, 
  Calendar,
  Smile,
  Meh,
  Frown,
  CloudRain,
  Sun,
  Cloud,
  Image,
  Lock,
  Unlock,
  ChevronRight,
  Heart
} from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Textarea } from "@/components/ui/textarea"

interface DiaryEntry {
  id: number
  date: string
  mood: "happy" | "neutral" | "sad"
  weather: "sunny" | "cloudy" | "rainy"
  content: string
  isPrivate: boolean
  likes?: number
}

interface MobileDiaryProps {
  onBack: () => void
}

export function MobileDiary({ onBack }: MobileDiaryProps) {
  const [isWriting, setIsWriting] = useState(false)
  const [selectedMood, setSelectedMood] = useState<string | null>(null)
  const [selectedWeather, setSelectedWeather] = useState<string | null>(null)
  const [diaryContent, setDiaryContent] = useState("")
  const [isPrivate, setIsPrivate] = useState(true)

  const diaryEntries: DiaryEntry[] = [
    {
      id: 1,
      date: "今天",
      mood: "happy",
      weather: "sunny",
      content: "今天和室友一起去图书馆学习，效率很高！晚上还一起吃了火锅，感觉生活充满了小确幸。",
      isPrivate: false,
      likes: 12,
    },
    {
      id: 2,
      date: "昨天",
      mood: "neutral",
      weather: "cloudy",
      content: "普通的一天，上课、作业、自习。虽然有些疲惫，但一切都在正轨上。",
      isPrivate: true,
    },
    {
      id: 3,
      date: "3月12日",
      mood: "sad",
      weather: "rainy",
      content: "考试没考好，有点失落。不过想想还有机会补救，给自己打打气吧。",
      isPrivate: true,
    },
  ]

  const moodOptions = [
    { id: "happy", icon: Smile, label: "开心", color: "text-success bg-success/10" },
    { id: "neutral", icon: Meh, label: "平静", color: "text-primary bg-primary/10" },
    { id: "sad", icon: Frown, label: "低落", color: "text-warning bg-warning/10" },
  ]

  const weatherOptions = [
    { id: "sunny", icon: Sun, label: "晴天" },
    { id: "cloudy", icon: Cloud, label: "阴天" },
    { id: "rainy", icon: CloudRain, label: "雨天" },
  ]

  const getMoodIcon = (mood: string) => {
    switch (mood) {
      case "happy": return <Smile className="h-4 w-4 text-success" />
      case "neutral": return <Meh className="h-4 w-4 text-primary" />
      case "sad": return <Frown className="h-4 w-4 text-warning" />
      default: return <Meh className="h-4 w-4" />
    }
  }

  const getWeatherIcon = (weather: string) => {
    switch (weather) {
      case "sunny": return <Sun className="h-4 w-4 text-accent" />
      case "cloudy": return <Cloud className="h-4 w-4 text-muted-foreground" />
      case "rainy": return <CloudRain className="h-4 w-4 text-primary" />
      default: return <Sun className="h-4 w-4" />
    }
  }

  if (isWriting) {
    return (
      <div className="flex flex-col min-h-screen bg-background">
        {/* Header */}
        <header className="sticky top-0 z-10 bg-card border-b border-border px-4 py-3">
          <div className="flex items-center justify-between">
            <Button variant="ghost" size="sm" onClick={() => setIsWriting(false)}>
              取消
            </Button>
            <span className="font-semibold text-foreground">写日记</span>
            <Button size="sm" disabled={!diaryContent.trim() || !selectedMood}>
              发布
            </Button>
          </div>
        </header>

        <main className="flex-1 px-4 py-4 space-y-4">
          {/* Mood Selection */}
          <div className="space-y-2">
            <p className="text-sm font-medium text-foreground">今天的心情</p>
            <div className="flex gap-3">
              {moodOptions.map((mood) => (
                <button
                  key={mood.id}
                  onClick={() => setSelectedMood(mood.id)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-full border transition-all ${
                    selectedMood === mood.id
                      ? `${mood.color} border-current`
                      : "border-border hover:border-primary/50"
                  }`}
                >
                  <mood.icon className="h-4 w-4" />
                  <span className="text-sm">{mood.label}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Weather Selection */}
          <div className="space-y-2">
            <p className="text-sm font-medium text-foreground">今天的天气</p>
            <div className="flex gap-3">
              {weatherOptions.map((weather) => (
                <button
                  key={weather.id}
                  onClick={() => setSelectedWeather(weather.id)}
                  className={`flex items-center gap-2 px-4 py-2 rounded-full border transition-all ${
                    selectedWeather === weather.id
                      ? "bg-primary/10 border-primary text-primary"
                      : "border-border hover:border-primary/50"
                  }`}
                >
                  <weather.icon className="h-4 w-4" />
                  <span className="text-sm">{weather.label}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Content */}
          <div className="space-y-2">
            <p className="text-sm font-medium text-foreground">写下今天的心情...</p>
            <Textarea
              value={diaryContent}
              onChange={(e) => setDiaryContent(e.target.value)}
              placeholder="今天发生了什么？你的感受如何？"
              className="min-h-[200px] resize-none"
            />
          </div>

          {/* Options */}
          <div className="flex items-center justify-between py-2">
            <Button variant="ghost" size="sm" className="text-muted-foreground">
              <Image className="h-4 w-4 mr-2" />
              添加图片
            </Button>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setIsPrivate(!isPrivate)}
              className={isPrivate ? "text-muted-foreground" : "text-primary"}
            >
              {isPrivate ? (
                <>
                  <Lock className="h-4 w-4 mr-2" />
                  仅自己可见
                </>
              ) : (
                <>
                  <Unlock className="h-4 w-4 mr-2" />
                  分享到社区
                </>
              )}
            </Button>
          </div>
        </main>
      </div>
    )
  }

  return (
    <div className="flex flex-col min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-10 bg-card border-b border-border px-4 py-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="icon" onClick={onBack}>
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <span className="font-semibold text-foreground">心情日记</span>
          </div>
          <Button variant="ghost" size="icon">
            <Calendar className="h-5 w-5" />
          </Button>
        </div>
      </header>

      {/* Stats Card */}
      <div className="px-4 pt-4">
        <Card className="border-0 bg-gradient-to-br from-primary/10 to-accent/10">
          <CardContent className="p-4">
            <div className="flex justify-around text-center">
              <div>
                <p className="text-2xl font-bold text-foreground">28</p>
                <p className="text-xs text-muted-foreground">累计记录</p>
              </div>
              <div className="w-px bg-border" />
              <div>
                <p className="text-2xl font-bold text-foreground">7</p>
                <p className="text-xs text-muted-foreground">连续天数</p>
              </div>
              <div className="w-px bg-border" />
              <div>
                <p className="text-2xl font-bold text-success">68%</p>
                <p className="text-xs text-muted-foreground">积极情绪</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Diary List */}
      <main className="flex-1 px-4 py-4 space-y-3 pb-24">
        {diaryEntries.map((entry) => (
          <Card key={entry.id} className="border border-border/50 shadow-sm hover:shadow-md transition-shadow">
            <CardHeader className="pb-2">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium text-foreground">{entry.date}</span>
                  {getMoodIcon(entry.mood)}
                  {getWeatherIcon(entry.weather)}
                </div>
                <div className="flex items-center gap-2">
                  {entry.isPrivate ? (
                    <Lock className="h-3 w-3 text-muted-foreground" />
                  ) : (
                    <Badge variant="secondary" className="text-[10px] flex items-center gap-1">
                      <Heart className="h-3 w-3" />
                      {entry.likes}
                    </Badge>
                  )}
                  <ChevronRight className="h-4 w-4 text-muted-foreground" />
                </div>
              </div>
            </CardHeader>
            <CardContent className="pt-0">
              <p className="text-sm text-muted-foreground line-clamp-2">{entry.content}</p>
            </CardContent>
          </Card>
        ))}
      </main>

      {/* FAB */}
      <Button
        size="lg"
        className="fixed bottom-24 right-4 h-14 w-14 rounded-full shadow-lg z-20"
        onClick={() => setIsWriting(true)}
      >
        <Plus className="h-6 w-6" />
      </Button>
    </div>
  )
}
